[versions]
versionCode = "325"
versionName = "3.0.0"

minSdk = "28"
compileSdk = "36"
targetSdk = "36"

# Libraries

activityCompose = "1.12.2"
agp = "8.13.2"
androidxLifecycle = "2.10.0"
# Used due to composeBom = "2025.12.00" LazyGrid bug
androidxFoundation = "1.11.0-alpha02"
appcompat = "1.7.1"
billing = "8.3.0"
coil = "3.3.0"
composeBom = "2025.12.01"
composeNavigation = "2.9.6"
coreKtx = "1.17.0"
datastore = "1.2.0"
firebaseBom = "34.7.0"
firebaseCrashlytics = "3.0.6"
flagkit = "1.0.5"
googleServices = "4.4.4"
immutableCollections = "0.4.0"
inAppReview = "2.0.2"
koinBom = "4.1.1"
kotlin = "2.3.0"
kotlinx-datetime = "0.7.1"
kotlinxSerialization = "1.9.0"
ktor = "3.3.3"
material = "1.13.0"
material3 = "1.5.0-alpha11"
material3Adaptive = "1.3.0-alpha05"
openapi = "7.18.0"
phoenix = "3.0.0"
qr = "1.0.1"
timber = "5.0.1"
tvFoundation = "1.0.0-alpha12"
tvMaterial = "1.0.1"
workManager = "2.11.0"
youtube-player = "13.0.0"
younify = "0.9.39"

# Testing Libraries

junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"

[libraries]
android-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
android-billing = { group = "com.android.billingclient", name = "billing-ktx", version.ref = "billing" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "androidxFoundation" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-compose-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "material3Adaptive" }
androidx-compose-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-work = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workManager" }

androidx-tv-foundation = { group = "androidx.tv", name = "tv-foundation", version.ref = "tvFoundation" }
androidx-tv-material = { group = "androidx.tv", name = "tv-material", version.ref = "tvMaterial" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "composeNavigation" }
androidx-datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
androidx-app-review = { group = "com.google.android.play", name = "review-ktx", version.ref = "inAppReview" }

coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil" }
coil-svg = { group = "io.coil-kt.coil3", name = "coil-svg", version.ref = "coil" }

kotlin-immutable-collections = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "immutableCollections" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-proto = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-protobuf", version.ref = "kotlinxSerialization" }

qr-compose = { group = "com.lightspark", name = "compose-qr-code", version.ref = "qr" }
youtube-player = { group = "com.pierfrancescosoffritti.androidyoutubeplayer", name = "core", version.ref = "youtube-player" }
youtube-player-ui = { group = "com.pierfrancescosoffritti.androidyoutubeplayer", name = "custom-ui", version.ref = "youtube-player" }
flagkit = { module = "com.github.murgupluoglu:flagkit-android", version.ref = "flagkit" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
phoenix = { group = "com.jakewharton", name = "process-phoenix", version.ref = "phoenix" }
younify = { module = "tv.younify.sdk:connect", version.ref = "younify" }

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-serialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-auth = { group = "io.ktor", name = "ktor-client-auth", version.ref = "ktor" }
ktor-client-logger = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koinBom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-android-work = { module = "io.insert-koin:koin-androidx-workmanager" }

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-config = { group = "com.google.firebase", name = "firebase-config" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }

junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
openapi-generator = { id = "org.openapi.generator", version.ref = "openapi" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }
