name: Main Flow

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Cache ktlint
        uses: actions/cache@v4
        with:
          path: ktlint
          key: ktlint-1.7.1

      - name: Setup ktlint
        run: |
          if [ ! -f ktlint ]; then
            curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.7.1/ktlint
            chmod a+x ktlint
          fi

      - name: Run ktlint
        run: ./ktlint
